{
  "user_service": {
    "timestamp": "2025-05-09T10:40:03.631789",
    "status": "unhealthy",
    "error": "HTTPConnectionPool(host='service_a', port=5000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffaa4ffb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
  },
  "order_service": {
    "timestamp": "2025-05-09T10:40:03.631789",
    "status": "healthy",
    "response_time": 0.001842
  },
  "inventory_service": {
    "timestamp": "2025-05-09T10:40:03.631789",
    "status": "healthy",
    "response_time": 0.001811
  },
  "notification_service": {
    "timestamp": "2025-05-09T10:40:03.631789",
    "status": "healthy",
    "response_time": 0.001294
  }
}